In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
#from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [10]:
img_matrix_x=[]
for line in open('X_matrix_image_clean.txt'):
    list_=line.split(' ')
    image_vec=np.array((list_[0:len(list_)]))
    image_vec_f=[float(i) for i in image_vec]
    img_matrix_x.append(image_vec_f)
    
img_matrix_y=[]
for line in open('Y_matrix_image_clean.txt'):
    list_=line.split(' ')
    image_vec=np.array((list_[0:len(list_)]))
    image_vec_f=[float(i) for i in image_vec]
    img_matrix_y.append(image_vec_f)    

In [19]:
N=np.shape(img_matrix_x)[0]
D=np.shape(img_matrix_x)[1]
#img_matrix_y=img_matrix_y.reshape(N,1)
img_matrix_y=np.array(img_matrix_y).T

In [20]:
np.shape(img_matrix_y)

(15064, 1)

In [21]:
img_matrix_y[0]

array([0.])

In [27]:

N=np.shape(img_matrix_x)[0]
D=np.shape(img_matrix_x)[1]

Y=np.random.randn(N)
X=np.zeros((N,D))

        
for i in range(N):
    Y[i]=np.round(img_matrix_y[i])    #expressions
    for j in range(D):
                
        X[i,j]=img_matrix_x[i][j]     #pixels into XX
 
       


In [29]:
np.shape(X)

(15064, 2304)

In [30]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=101)

In [31]:
logmodel=LogisticRegression()

In [32]:
logmodel.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [33]:
train_predict=logmodel.predict(X_train)

In [35]:
print(classification_report(Y_train,train_predict))

             precision    recall  f1-score   support

        0.0       0.76      0.69      0.73      4195
        1.0       0.81      0.86      0.83      6349

avg / total       0.79      0.79      0.79     10544



In [38]:
print(confusion_matrix(Y_train,train_predict)) #overall my own code is 0.76 vs 0.79 here for classification rate

[[2893 1302]
 [ 891 5458]]


In [39]:
test_predict=logmodel.predict(X_test)

In [40]:
print(classification_report(Y_test,test_predict))

             precision    recall  f1-score   support

        0.0       0.61      0.55      0.58      1881
        1.0       0.70      0.75      0.73      2639

avg / total       0.66      0.67      0.66      4520



In [41]:
print(confusion_matrix(Y_test,test_predict))   #overall my own code better 0.71 (vs. 0.66)even when not completely converged yet than this in test set but slower 

[[1029  852]
 [ 652 1987]]
